version: 2.1

jobs:
  build:
    docker:
      - image: rundeck/ci@sha256:5405395ca6ca39285e2289b4508b0f6d026c90ce6c2423bc02533031d4e3f28f
    steps:
      - checkout
      - run: npm install
      - run: npm run build
