swagger: '2.0'
info:
  version: 1.0.0
  title: Rundeck
  license:
    name: MIT
basePath: '/api/26'
schemes:
- http
produces:
- application/json
consumes:
- application/json

paths:
  /project/{project}/jobs:
    get:
      summary: List the jobs that exist for a project
      operationId: jobList
      tags:
      - project
      - job
      parameters:
      - name: project
        in: path
        required: True
        description: Project name
        type: string
      - name: idList
        in: query
        required: false
        description: Comma separated list of Job IDs to include
        type: string
      - name: groupPath
        in: query
        required: false
        description: Group or partial group path to include all jobs within that group path. Set to the special value "-" to match the top level jobs only.
        default: '*'
        type: string
      - name: jobFilter
        in: query
        required: false
        description: A filter for the job name. Matches any job name that contains this value.
        type: string
      - name: jobExactFilter
        in: query
        required: false
        description: An exact job name to match.
        type: string
      - name: groupPathExact
        in: query
        required: false
        description: An exact group path to match. Set to the special value "-" to match the top level jobs only.
        type: string
      - name: scheduledFilter
        in: query
        required: false
        description: Specify whether to return only scheduled or only not scheduled jobs.
        type: boolean
      - name: serverNodeUUIDFilter
        in: query
        required: false
        description: In cluster mode, use to select scheduled jobs assigned to the server with the given UUID.
        type: string
      responses:
        '200':
          description: Expected response to a valid request
          schema: {type: array, items: {$ref: '#/definitions/Job'}}

  /job/{id}/executions:
    get:
      summary: List job executions
      operationId: jobExecutionList
      tags:
      - job
      - execution
      parameters:
      - name: id
        in: path
        required: True
        description: Job ID
        type: string
      responses:
        '200':
          description: List of executions for job
          schema: {$ref: '#/definitions/ExecutionList'}
    post:
      summary: Run the specified job
      operationId: jobExecutionRun
      tags:
      - job
      - execution
      parameters:
      - name: id
        in: path
        required: True
        description: Job ID
        type: integer
      - name: request
        in: body
        required: false
        schema: {$ref: '#/definitions/ExecuteJobRequest'}
      responses:
        '200':
          description: Expected response for a valid request
          schema: {$ref: '#/definitions/ExecutionList'}
    delete:
      summary: Delete all job executions
      operationId: jobExecutionDelete
      tags:
      - job
      - execution
      parameters:
      - name: id
        in: path
        required: True
        description: Job ID
        type: integer
      responses:
        '204':
          description: Content deleted
          schema: {$ref: '#/definitions/JobExecutionDelete'}
  
  /job/{jobID}/retry/{executionID}:
    post:
      summary: Retry a failed job execution on failed nodes only or on the same as the execution. This is the same functionality as the `Retry Failed Nodes ...` button on the execution page.
      operationId: jobRetryExecution
      tags:
      - job
      - execution
      parameters:
      - name: jobID
        in: path
        required: true
        type: string
      - name: executionID
        in: path
        required: true
        type: integer
      - name: Request
        in: body
        required: false
        schema: {$ref: '#/definitions/RetryExecutionRequest'}
      responses:
        '200':
          description: Exected response to a valid request.
          schema: {$ref: '#/definitions/ExecutionList'}

  /job/{id}:
    get:
      summary: Export a single job definition in XML or YAML formats.
      operationId: jobGet
      tags:
      - job
      parameters:
      - name: id
        in: path
        required: True
        description: ID of the job to export.
        type: string
      - name: format
        in: query
        required: false
        type: string
        enum: ['xml', 'yaml']
        default: xml
      responses:
        '200':
          description: Expected response to a valid request.
          schema:
            properties:
              content: {type: string}
    delete:
      summary: Delete a single job definition.
      operationId: jobDelete
      tags:
      - job
      parameters:
      - name: id
        in: path
        required: True
        description: ID of job to delete.
        type: number
      responses:
        '204':
          description: Job was deleted.
        '404':
          description: Job not found.

  /job/{id}/info:
    get:
      summary: Get metadata about a specific job.
      operationId: jobInfoGet
      tags:
      - job
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Expected response to a valid request.
          schema: {$ref: '#/definitions/JobMetadata'}

  /jobs/delete:
    post:
      summary: Delete multiple job definitions at once
      operationId: jobBulkDelete
      tags:
      - job
      - bulk
      parameters:
      - name: JobBulkDeleteRequest
        in: body
        required: true
        schema:
          required:
          - ids
          properties:
            ids:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Job deleted response
          schema: {$ref: '#/definitions/JobBulkOperationResponse'}

  /job/{id}/execution/enable:
    post:
      summary: Enable executions for a job. (ACL requires toggle_execution action for a job.)
      operationId: jobExecutionEnable
      tags:
      - job
      - execution
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: Job executions enabled
          schema:
            properties: {success: {type: boolean}}

  /job/{id}/execution/disable:
    post:
      summary: Disable all executions for a job (scheduled or manual). (ACL requires toggle_execution action for a job.)
      operationId: jobExecutionDisable
      tags:
      - job
      - execution
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: Job executions disabled
          schema:
            properties: {success: {type: boolean}}

  /job/{id}/schedule/enable:
    post:
      summary: Enable the schedule for a job. (ACL requires toggle_schedule action for a job.)
      operationId: jobScheduleEnable
      tags:
      - job
      - schedule
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: Job schedule enabled
          schema:
            properties: {success: {type: boolean}}

  /job/{id}/schedule/disable:
    post:
      summary: Disable the schedule for a job. (ACL requires toggle_schedule action for a job.)
      operationId: jobScheduleDisable
      tags:
      - job
      - schedule
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: Job schedules disabled
          schema:
            properties: {success: {type: boolean}}

  /jobs/execution/enable:
    post:
      summary: Bulk enable job executions
      operationId: jobExecutionBulkEnable
      tags:
      - job
      - execution
      parameters:
      - name: JobExecutionBulkEnableRequest
        in: body
        required: true
        schema:
          required:
          - ids
          properties:
            ids:
              type: array
              items: {type: string}
      responses:
        '200':
          description: Job deleted response
          schema: {$ref: '#/definitions/JobBulkOperationResponse'}

  /jobs/execution/disable:
    post:
      summary: Bulk disable job executions
      operationId: jobExecutionBulkDisable
      tags:
      - job
      - execution
      parameters:
      - name: JobExecutionBulkDisableRequest
        in: body
        required: true
        schema:
          required:
          - ids
          properties:
            ids:
              type: array
              items: {type: string}
      responses:
        '200':
          description: Job toggle execution response
          schema: {$ref: '#/definitions/JobBulkOperationResponse'}

  /jobs/schedule/enable:
    post:
      summary: Bulk enable job schedule
      operationId: jobScheduleBulkEnable
      tags:
      - job
      - schedule
      parameters:
      - name: JobScheduleBulkEnableRequest
        in: body
        required: true
        schema:
          required:
          - ids
          properties:
            ids:
              type: array
              items: {type: string}
      responses:
        '200':
          description: Job toggle schedule response
          schema: {$ref: '#/definitions/JobBulkOperationResponse'}

  /jobs/schedule/disable:
    post:
      summary: Bulk disable job schedule
      operationId: jobScheduleBulkDisable
      tags:
      - job
      - schedule
      parameters:
      - name: JobScheduleBulkDisableRequest
        in: body
        required: true
        schema:
          required:
          - ids
          properties:
            ids:
              type: array
              items: {type: string}
      responses:
        '200':
          description: Job toggle schedule response
          schema: {$ref: '#/definitions/JobBulkOperationResponse'}

  /job/{id}/input/file:
    post:
      summary: Upload file as job option
      operationId: jobInputFileUpload
      tags:
      - job
      consumes:
        - octet/stream
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: optionName
        in: query
        required: true
        type: string
      - name: fileName
        in: query
        required: true
        type: string
      - name: File
        in: body
        required: true
        x-ms-parameter-location: method
        schema:
          type: object
          format: file
      responses:
        '200':
          description: Yay

  /job/{id}/input/files:
    get:
      summary: List uploaded input files for job
      operationId: jobInputFileUpload
      tags:
      - job
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: List of input files
          schema: {$ref: '#/definitions/JobInputFileListResponse'}

  /jobs/file/{id}:
    get:
      summary: Get job input file info
      operationId: jobInputFileInfoGet
      tags:
      - job
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Job input file info
          schema: {$ref: '#/definitions/JobInputFileInfo'}

definitions:
  $ref: definitions.yaml 