swagger: '2.0'
info:
  version: 1.0.0
  title: Rundeck
  license:
    name: MIT
basePath: '/api/26'
schemes:
- http
produces:
- application/json
consumes:
- application/json

paths:
  /metrics:
    get:
      summary: List links to enabled Metrics endpoints
      operationId: metricList
      responses:
        '200':
          description: List of Metrics endpoint links
          schema:
            type: object
            required:
            - _links
            properties:
              _links:
                type: object
                required:
                - metrics
                - ping
                - threads
                - healthcheck
                properties:
                  metrics: {properties: {
                    href: {type: string}},
                    required: [href]}
                  ping: {properties: {
                    href: {type: string}},
                    required: [href]}
                  threads: {properties: {
                    href: {type: string}},
                    required: [href]}
                  healthcheck: {properties: {
                    href: {type: string}},
                    required: [href]}