swagger: '2.0'
info:
  version: 1.0.0
  title: Rundeck
  license:
    name: MIT
basePath: '/api/26'
schemes:
- http
produces:
- application/json
consumes:
- application/json

paths:
  /projects:
    get:
      summary: List projects
      operationId: projectList
      tags:
      - project
      responses:
        '200':
          description: List of projects
          schema:
            type: array
            items:
              type: object
              properties:
                name:        {type: string}
                description: {type: string}
                url:         {type: string}
    post:
      summary: Create a new project
      operationId: projectCreate
      tags:
      - project
      parameters:
      - name: ProjectCreateRequest
        in: body
        required: true
        schema:
          properties:
            name:   {type: string}
            config: {type: object}
      responses:
        '201': {description: Project created}

  /project/{project}:
    get:
      summary: Get information about a project
      operationId: projectGet
      parameters:
      - name: project
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Project info
          schema: {$ref: '#/definitions/Project'}
    delete:
      summary: Delete project
      operationId: projectDelete
      parameters:
      - name: project
        in: path
        required: true
        type: string
      responses:
        '204': {description: Content deleted}

  /project/{project}/config:
    get:
      summary: Get project config
      operationId: projectConfigGet
      parameters:
      - name: project
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Project info
          schema: {type: object}
    put:
      summary: Update project config
      operationId: projectConfigUpdate
      parameters:
      - name: project
        in: path
        required: true
        type: string
      - name: ProjectConfigUpdateRequest
        in: body
        required: true
        schema: {type: object}
      responses:
        '200': {description: Project config updated}

  /project/{project}/config/{key}:
    get:
      summary: Get project config key
      operationId: projectConfigKeyGet
      parameters:
      - name: project
        in: path
        required: true
        type: string
      - name: key
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Project config key and value
          schema:
            properties:
              key:   {type: string}
              value: {type: string}
    put:
      summary: Get project config key
      operationId: projectConfigKeySet
      parameters:
      - name: project
        in: path
        required: true
        type: string
      - name: key
        in: path
        required: true
        type: string
      - name: ProjectConfigKeySetRequest
        required: true
        in: body
        schema:
          properties:
            value: {type: string}
      responses:
        '200':
          description: Project config key set
          schema:
            properties:
              key:   {type: string}
              value: {type: string}
    delete:
      summary: Delete project config key
      operationId: projectConfigKeyDelete
      parameters:
      - name: project
        in: path
        required: true
        type: string
      - name: key
        in: path
        required: true
        type: string
      responses:
        '204': {description: Content deleted}

  /project/{project}/jobs/export:
    get:
      summary: Export the job definitions in XML or YAML formats.
      operationId: projectJobsExport
      tags:
      - job
      - project
      parameters:
      - name: project
        in: path
        required: True
        description: The project to export jobs for.
        type: string
      - name: format
        in: query
        required: false
        description: XML or YAML format for exported jobs.
        type: string
        enum: ['xml', 'yaml']
        default: xml
      - name: idlist
        in: query
        required: false
        description: A comma-separated list of Job IDs to export.
        type: string
      - name: groupPath
        in: query
        required: false
        description: Group or partial group path to include all jobs within that group path.
        type: string
      - name: jobFilter
        in: query
        required: false
        description: Filter for the job Name.
        type: string
      responses:
        '200':
          description: Expected response to a valid request.
          schema: {type: string}

  /project/{project}/jobs/import:
    post:
      summary: Import job definitions in XML or YAML formats.
      operationId: projectJobsImport
      tags:
      - job
      - project
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      responses:
        '200': {description: Expected response to a valid request.}

  /project/{project}/import:
    put:
      summary: Import project archive.
      operationId: projectArchiveImport
      tags:
      - job
      - project
      consumes:
         - application/zip
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      - name: jobUuidOption
        in: query
        type: string
        enum: [preserve, remove]
        default: remove
      - name: importExecutions
        in: query
        type: boolean
      - name: importConfig
        in: query
        type: boolean
      - name: importACL
        in: query
        type: boolean
      - name: File
        in: body
        required: true
        x-ms-parameter-location: method 
        schema:
          type: object
          format: file
      responses:
        '200': {description: Expected response to a valid request}

  /project/{project}/export:
    get:
      summary: Export archive of project synchronously
      operationId: projectArchiveExportSync
      produces:
      - application/zip
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      - name: executionIds
        in: query
        description: A list (comma-separated) of execution IDs. If this is specified then the archive will contain only executions that are specified, and will not contain Jobs, ACLs, or project configuration/readme files.
        type: boolean
      - name: exportAll
        in: query
        description: Export all project resources
        type: boolean
        default: true
      - name: exportJobs
        in: query
        description: Export all project resources
        type: boolean
      - name: exportExecutions
        in: query
        description: Export all project resources
        type: boolean
      - name: exportConfigs
        in: query
        description: Export all project resources
        type: boolean
      - name: exportReadmes
        in: query
        description: Export all project resources
        type: boolean
      - name: exportAcls
        in: query
        description: Export all project resources
        type: boolean
      responses:
        '200':
          description: Zip archive
          schema:
            type: object
            format: file

  /project/{project}/readme.md:
    get:
      summary: Get the readme.md contents
      operationId: projectReadmeGet
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      responses:
        '200':
          description: readme.md contents
          schema:
            properties:
              contents: {type: string}
        '404': {description: The file does not exist}
    put:
      summary: Create or modify project README.md
      operationId: projectReadmePut
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      - name: ReadmeUpdateRequest
        in: body
        required: True
        schema:
          properties:
            contents: {type: string}
      responses:
        '200': {description: Expected response to a valid request}
    delete:
      summary: Delete project README.md
      operationId: projectReadmeDelete
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      responses:
        '204': {description: No Content}

  /project/{project}/motd.md:
    get:
      summary: Get the readme.md contents
      operationId: projectMotdGet
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      responses:
        '200':
          description: motd.md contents
          schema:
            properties:
              contents: {type: string}
        '404': {description: The file does not exist}
    put:
      summary: Create or modify project MOTD.md
      operationId: projectMotdPut
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      - name: MotdUpdateRequest
        in: body
        required: True
        schema:
          properties:
            contents: {type: string}
      responses:
        '200': {description: Expected response to a valid request.}
    delete:
      summary: Delete project motd.md
      operationId: projectMotdDelete
      parameters:
      - name: project
        in: path
        required: True
        description: Name of the project to import jobs into.
        type: string
      responses:
        '204': {description: No Content}